services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - trading_network
    mem_limit: 512m  # Limit memory usage
    cpus: 0.5        # Limit CPU usage

  trading_bot:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_TYPE=postgresql
    restart: unless-stopped
    command: python AlgoTrade.py
    container_name: algo_trading_bot
    tty: true
    stdin_open: true
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - trading_network
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "pgrep", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 1g   # Limit memory usage
    cpus: 1.0       # Limit CPU usage

networks:
  trading_network:
    driver: bridge

volumes:
  pgdata: 